.node: &node
  image: node:8.11.1
  before_script:
    - npm run gtfd
    - npm install
    - npm run goback
    - npm install -g firebase-tools

cache:
     key: "$CI_COMMIT_REF_NAME"
     paths:
        -   node_modules/

production_server_deployment:
  script:
     - npm run set_production_environment
     - npm run deploy
  only:
     - master

test_server_deployment:
  script:
     - npm run set_development_environment
     - npm run deploy
  only:
    -  develop