.node: &node
  image: node:8.11.1
  before_script:
    - npm run gtfd
    - npm install
    - npm run goback
    - npm install -g firebase-tools

cache:
     key: "$CI_COMMIT_REF_NAME"
     paths:
        -   node_modules/

stages:
    - production_server_deployment
    - test_server_deployment
    - dashboard_deployment

production_server_deployment:
  stage: production_server_deployment
  environment:
    name: production
  <<: *node
  script:
     - npm run set_production_environment
     - npm run deploy
  only:
     - master

test_server_deployment:
  stage: test_server_deployment
  environment:
     name: testDeployment
  <<: *node
  script:
     - npm run set_development_environment
     - npm run deploy
  only:
    -  develop

dashboard_deployment:
   image: ruby:latest
   script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=clothx-dashboard --api-key=$HEROKU_API_KEY