.node: &node
  image: node:8.11.1
  before_script:
    - npm run gtfd
    - npm install
    - npm run goback
    - npm install -g firebase-tools

cache:
     key: "$CI_COMMIT_REF_NAME"
     paths:
        -   node_modules/

stages:
    - production_server_deployment
    - test_server_deployment

production_server_deployment:
  stage: production_server_deployment
  environment:
    name: production
  <<: *node
  script:
     - firebase use clothxnet --token $FIREBASE_ACCESS_TOKEN
     - npm run deploy
  only:
     - master

test_server_deployment:
  stage: test_server_deployment
  environment:
     name: testDeployment
  <<: *node
  script:
     - firebase use clothxtest --token $FIREBASE_ACCESS_TOKEN
     - npm run deploy
  only:
    -  develop
     